version: '3'
services:
  elasticsearch:
    container_name: queensland_elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    volumes:
      - ./backups:/mount/backups
    environment:
      - path.repo=/mount/backups
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    container_name: queensland_kibana
    image: docker.elastic.co/kibana/kibana:6.4.1
    ports:
      - "5601:5601"
