version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - npm i
      - MONGO_URL=$MONGO_URL MONGO_DB=$MONGO_DB npm run migrate-up
artifacts:
  files:
    - "**/*"
  name: SitedAPIMigration.zip
  base-directory: definitions
